### PR TITLE
Plain js with objects

### PR DESCRIPTION
**Pull request by yghoor**
### Plain JavaScript with objects done according to spec from curriculum-javascript/books/m1_plain_js_objects.md

> **https://htmlpreview.github.io/?https://github.com/yghoor/awesome-books/blob/plain-js-with-objects/index.html**

### CODE REVIEW

**Comment by Cerdtruir** [comment]
your linter files shouldnt be committed

**Comment by yghoor** [comment]
> your linter files shouldnt be committed

Okay I removed it in the last branch

**Review by Cerdtruir — COMMENTED** [review]
Please reorder code in latest branch

**Review by Cerdtruir — APPROVED** [review]

**Comment by yghoor** [comment]
Re-ordering completed in latest branch

**Pull request merged**
